// Generated by https://pagedraw.io/pages/6179
import React from 'react';
import './dropdownclosed.css';

function render() {
    return <div className="dropdownclosed">
        <div className="dropdownclosed-0">
            <div className="dropdownclosed-dropdownclosed-1">
                <div className="dropdownclosed-0-0-0">
                    <div className="dropdownclosed-rectangle-9">
                        <div className="dropdownclosed-0-0-0-0-0">
                            <div onClick={this.props.handleOpen} className="dropdownclosed-rectangle-3">
                                <div className="dropdownclosed-0-0-0-0-0-0-0">
                                    <div className="dropdownclosed-label-7">
                                        { this.props.chosen }
                                    </div>
                                    <div className="dropdownclosed-0-0-0-0-0-0-0-1">
                                        <div className="dropdownclosed-0-0-0-0-0-0-0-1-0">
                                            <img src="https://ucarecdn.com/dfea1260-4f66-45e6-a1f4-9eb1c437fec1/" className="dropdownclosed-image-4" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}