// Generated by https://pagedraw.io/pages/6179
import DropdownWrapper from '../Dropdown';
import Dropdownclosed from './dropdownclosed';
import React from 'react';
import './dropdown.css';

function render() {
    return <div className="dropdown">
        <div className="dropdown-0">
            <div className="dropdown-dropdown-0">
                <DropdownWrapper chosen={this.props.chosen} items={this.props.items} />
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}