// Generated by https://pagedraw.io/pages/6179
import React from 'react';
import './dropdownitem.css';

function render() {
    return <div className="pd-onactive-parent pd-onhover-parent dropdownitem">
        { (("A") == "A") ?
            <div className="dropdownitem-0-0">
                <div className="dropdownitem-0-0-0">
                    <div className="dropdownitem-a-6">
                        <div className="dropdownitem-0-0-0-0-0">
                            <div className="dropdownitem-pointer-9">
                                <div className="dropdownitem-0-0-0-0-0-0-0">
                                    <div className="dropdownitem-label-8">
                                        { this.props.label }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
        <div className="pd-onactive dropdownitem-1">
            <div className="dropdownitem-1-0">
                <div className="dropdownitem-a_active-3">
                    <div className="dropdownitem-1-0-0-0">
                        <div className="dropdownitem-pointer-4">
                            <div className="dropdownitem-1-0-0-0-0-0">
                                <div className="dropdownitem-label-0">
                                    { this.props.label }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="pd-onhover dropdownitem-2">
            <div className="dropdownitem-2-0">
                <div className="dropdownitem-a_hover-1">
                    <div className="dropdownitem-2-0-0-0">
                        <div className="dropdownitem-pointer-0">
                            <div className="dropdownitem-2-0-0-0-0-0">
                                <div className="dropdownitem-label-5">
                                    { this.props.label }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}