// Generated by https://pagedraw.io/pages/6179
import Dropdownitem from './dropdownitem';
import React from 'react';
import './dropdownopen.css';

function render() {
    return <div className="dropdownopen">
        <div className="dropdownopen-0">
            <div className="dropdownopen-dropdownopen-3">
                <div className="dropdownopen-0-0-0">
                    <div className="dropdownopen-rectangle-8">
                        <div className="dropdownopen-0-0-0-0-0">
                            <div onClick={this.props.handleOpen} className="dropdownopen-rectangle-1">
                                <div className="dropdownopen-0-0-0-0-0-0-0">
                                    <div className="dropdownopen-label-8">
                                        { this.props.chosen }
                                    </div>
                                    <div className="dropdownopen-0-0-0-0-0-0-0-1">
                                        <div className="dropdownopen-0-0-0-0-0-0-0-1-0">
                                            <img src="https://ucarecdn.com/dfea1260-4f66-45e6-a1f4-9eb1c437fec1/" className="dropdownopen-image-2" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="dropdownopen-0-0-0-0-1">
                            <div className="dropdownopen-0-0-0-0-1-0">
                                { this.props.items.map((item, i) => {
                                    return <div key={i} onClick={item.handler} className="dropdownopen-rectangle_2">
                                        <div className="dropdownopen-0-0-0-0-1-0-0-0-0">
                                            <div className="dropdownopen-instance_of_deleted_component-0">
                                                <Dropdownitem label={item.label} /> 
                                            </div>
                                        </div>
                                    </div>;
                                }) }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}